version: '3'

services:
  FastApiCrud:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
#    environment:
#      FLASK_APP: run.py
#      FLASK_ENV: development
#      SECRET_KEY: your_secret_key
#      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@db:5432/tasks

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: android2
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: