version: '3'

services:
  fastapicrud:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://android2:admin@postgresql:5432/blog
      - SECRET_KEY=ANDROID
      - ALGORITHM=HS256


  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: android2
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
