
version: '3'

services:
  fastapicrud:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://android2:admin@postgresql:5432/blog
      - SECRET_KEY=ANDROID
      - ALGORITHM=HS256


  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: android2
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:

